server:
  port: 80

spring:
  application:
    name: demo-business

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: demo-business
    prefer-ip-address: true     #访问路径可以显示IP地址

# eureka 注册详细里面 使用$$取值请在pom中加入maven插件
info:
  app.name: business-app
  company.name: highzap
# 使用 @@ 为 ${} 必须使用插件.--> 父工程pom 下的 pluginManagement maven-resources-plugin
  build.artifactId: @project.artifactId@
  build.version: @project.version@

